### ISSUE TITLE
Issue #95, #115 question, subcommands with global options

### ISSUE THREAD

**Issue by ytti** [leejarvis/slop#134]
I can't see way to have option before subcommands, which would be visible in all subcommands as well

Consider I have
    on :t, :topic=, "Topic, defaults to #{TOPIC}", :default=>TOPIC

    command 'put' do                                                                                                                    
      description 'put message to MQ'
      on :t, :topic=, "Topic, defaults to #{TOPIC}", :default=>TOPIC
      run do |opts, args|
        mq_put opts, args
      end
    end

    command 'get' do
      description 'get message from MQ'
      on :t, :topic=, "Topic, defaults to #{TOPIC}", :default=>TOPIC
      on :p, :pretty, 'Pretty print JSON'
      run do |opts, args|
        mq_get opts, args
      end

if i do ./script -t foobar put hello

then commands are not ran, it seems to expect command to be appear first

if i do ./script put -t foobar hello

it works as expected, but it's subcommand option, and i have to specify it for each subcommand

It might be by-design, not sure, but I would gather people may want to have options seen in each subcommand?

**Comment by clooth** [comment]
Any updates on this yet?

**Comment by leejarvis** [comment]
@clooth I'm sorry to inform you that git-style subcommands did not make the cut for version 4. I don't plan on iterating them much for version 3 because it would require quite a lot of work and there are so many questions around it.

As I mention in the README I'd be keen to build something that wrapped Slop v4 to provide support for these subcommands. However, I haven't found many people that use that (they tend to use something beefier like Thor) so it's not really at the top of my list of things to do. If you're interested on working on something like that though, please let me know.

I'm going to close this, based on my comment above regarding v3.
