### ISSUE TITLE
Support end of command options

### ISSUE THREAD

**Issue by uri** [leejarvis/slop#159]
I'm running into a problem when I try to pass another ruby file as a parameter.

    ruby slop_test.rb -f lower_ruby/a.rb

It's seems like ruby is actually running `lower/a.rb`

This problem also has to with rbenv automatically selecting the ruby version. Which causes rbenv to find a `.ruby-version` and set the version accordingly.

Using an end of command terminator (`--`) it stops ruby from running the second file but then slop doesn't work.

### Reproducing

```bash
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
$ mkdir lower_ruby
$ cd lower_ruby
$ rbenv local 1.9.3-p551
$ touch a.rb
$ cd ..
$ ruby slop_test.rb -f lower_ruby/a.rb
# Errors using wrong ruby version which uses slop 3
$ ruby slop_test.rb -- -f lower_ruby/a.rb
{:file=>nil}
$ ruby slop_test.rb -- --file lower_ruby/a.rb
{:file=>nil}
```

### slop_test.rb

```ruby
#!/usr/bin/env ruby
require 'slop'

opts = Slop.parse do |o|
  o.string '-f', '--file', 'a file'
end

p opts.to_hash
```

**Comment by leejarvis** [comment]
Maybe this is a problem with the shim rbenv uses? Seems like it's slurping `*.rb` or something. I don't use rbenv so I'm not sure. It works fine for me so I don't think it's a Slop problem.

It won't work using the end of commands terminator because you're telling Ruby to ignore these things as options, and Slop handles that as it should.

Could you try the same code on a non-rbenv environment? If that's the cause then I'm afraid I don't have any better suggestions. I imagine you'd be able to reproduce the problem with optparse as well

**Comment by uri** [comment]
Thanks for the reply @leejarvis, but I think this *is* heavily related to `rbenv`. Either way, it's simple enough to call `ARGV.shift` beforehand.
