### ISSUE TITLE
Parsing nil raises an exception in parser.rb

### ISSUE THREAD

**Issue by dg1727** [leejarvis/slop#196]
The parser can be called like so:  

`opts = Slop.parse(array, suppress_errors: true) do |o|`
`o.bool  # etc.`
`# ...`
`end`

... where "array" is an alternative to the default of ARGV.  

If the client code passes nil instead of an array, then a NoMethodError is raised in parser.rb.  Nil could be passed if, for example, the client code miscalculates an index into `ARGV[]`, pointing to a single element that's one higher than the last element.  

I think this is a kind of error that could go unnoticed until runtime.  Client code may fail to `rescue` this error, since the only errors mentioned in the Slop readme are Slop::MissingArgument, Slop::UnknownOption, and Slop::Error, none of which include NoMethodError.  Also, the backtrace points to parser.rb as the error location (more prominently than to the client code).  So maybe type checking can be added to Slop to prevent this?  

If Slop receives nil for an array, it may be reasonable to treat this the same as if an empty array were passed, rather than raising an exception at all?  

Thanks for considering this.

**Comment by leejarvis** [comment]
Why would `nil` ever be passed? I'm not sure I understand a miscalculation for an index in `ARGV` because the method expects an array and not a single element inside of an array.

I don't like the idea of handling `nil`. Developers using Slop should be aware of the API and that `parse` expects an array or defaults to `ARGV`. Thus, solving it for `nil` values would be simple for developers: `Slop.parse Array(array_or_nil)`
