### ISSUE TITLE
Not correctly handling options containing a dash"

### ISSUE THREAD

**Issue by lbriais** [leejarvis/slop#204]
When an option name contains a dash like `--option-with-dash` the resulting of the parsing is wrong:
```ruby
opts = Slop::Options.new
opts.bool "--option-with-dash", 'Stupid option'
parser = Slop::Parser.new(opts)
parser.parse([]).to_hash # => {:option_with_dash=>false}
parser.parse(%w(--option-with-dash)).to_hash # => {:option_with_dash=>true}
```
This leads to horrible headaches as all __dashes are replaced by underscores__ with no reason...

**Comment by leejarvis** [comment]
Actually this is intentional since fd0e2d8bc3d1c647e6b051f48b8bedbe77934c0c -- to make the keys more symbol friendly. Perhaps we could have a config setting to disable this. WDYT?

**Comment by lbriais** [comment]
A config setting would be perfect for me.

The problem I face with such behaviour is that I am generating options dynamically with arbitrary names I can't guess in advance, and which could potentially contain both underscores and dashes...

**Comment by leejarvis** [comment]
Thanks @lbriais. 

> Or a more generic front, I doubt non-reversible transformations as a default behaviour are a good option. You may consider the untransformed names as default and condition the current behaviour to the config setting you suggested to introduce.

I somewhat agree. The suggestion is unfortunately non backwards compatible, though. I think having a config setting that *does not* do any transformation would be a good first step, then in a later version we can consider switching the config setting.

It's worth mentioning that we're doing this because using symbols as hash keys is considered canonical. Maybe this isn't the best choice, but since we do this, we prefer to use `:foo_bar` instead of `:"foo-bar"`

Do you fancy taking a shot at implementing this config option in a PR?

**Comment by lbriais** [comment]
See PR #206
