### ISSUE TITLE
Request for information: implementing commands.

### ISSUE THREAD

**Issue by thomasdziedzic** [leejarvis/slop#210]
Hi,

today I have a use case for adding commands into my terminal application. I need to implement a couple of commands which accomplish different tasks.

I found the commands section in the readme https://github.com/leejarvis/slop/commit/9550f868435779d7ed271beba496dc05478280bb

I also found https://github.com/leejarvis/slop/issues/155 which was closed with no reason given.

Do you have suggestions for other libraries that have this feature?

How hard would it be to implement some similar command functionality into slop itself? Could you give a high level description of the problem currently? Or is #155 still relevant?

Thanks for your time!

**Comment by leejarvis** [comment]
Hi,

#155 was closed because I never intended to implement command functionality in Slop. Instead, it proposed how one might do this in an extension of some sort. It's definitely still relevant. 

As I mentioned in that issue, I have no plans to build this into Slop. I would  welcome a third-party extension (and would be happy to help review). There's many ways to implement command support, and that's one of the reasons it's not baked into Slop. There's a lot of choices to make, and so it often makes sense for the user to just build the functionality they desire directly into their app. This is still an approach I would recommend.
