### ISSUE TITLE
Misleading block syntax example

### ISSUE THREAD

**Issue by ticky** [leejarvis/slop#213]
Hi there,

I was trying to set up a project to use slop, and following the example in the readme, I was under the impression the block syntax shown here;

```ruby
opts = Slop.parse do |o|
  # ...
  o.on '--version', 'print the version' do
    puts Slop::VERSION
    exit
  end
end
```

Was a generic method for receiving callbacks after parsing to perform certain operations. So I set up something like this;

```ruby
Slop.parse do |o|
  o.on '--do-a-thing', 'Perform some kind of operation' do
    do_thing(window: o[:thing_index])
    exit
  end

  o.integer '--thing-index', 'thing to operate on'

  o.on '--version', 'print the version' do
    puts Slop::VERSION
    exit
  end
end
```

It appears, however, that the above example was actually a hack taking advantage of an argument preprocessing callback which is not otherwise documented to that effect, and my attempt to use it failed in an unexpected way (`` `method_missing': undefined method `[]' for #<Slop::Options:0x007f9eb92ae108> (NoMethodError)``).

I believe it would be worthwhile to make note of this in the readme, as it’s a useful hack but may appear to the inexperienced to provide functionality it does not!

**Comment by leejarvis** [comment]
Hi Jessica, thanks for reporting.

> Was a generic method for receiving callbacks after parsing to perform certain operations

The *after parsing* part is what's incorrect. These blocks are executed during parse-time, rather than "finish" time. I wouldn't consider it a hack myself, though I concede that it's not obvious and not documented well. OptionParser does the same thing:

```
require "optparse"

opts = OptionParser.new { |o|
  o.on "-a" do
    puts "A"
  end

  o.on "-b" do
    puts "B"
  end
}

opts.parse! %w(-a -b) #=> prints A then B
opts.parse! %w(-b -a) #=> prints B then A
```

To achieve what you're looking for you could use a [custom type](https://github.com/leejarvis/slop#custom-option-types) and implement the `finish` method. Obviously it's not ideal, but it's one way it could be done. 

I'll have a think about how the README can improve this. If you have any suggestions it would be great to hear them. I find this sort of stuff can be difficult to explain and I've tried to avoid getting too technical in the basic parts of the README.

**Comment by ticky** [comment]
Thanks for taking on the feedback 😄

I didn’t mean “hack” maliciously at all, it just seems to me from the code that calls the block that it’s definitely taking advantage of a side effect of the behaviour!

I’d suggest it might be worth documenting the blocks’ use for mutating input values first, and having the “version” and “help” shortcuts be called out with something along the lines of “if you have options which don’t require any further option processing, you can react to them immediately by passing a block”!

**Comment by leejarvis** [comment]
Thanks Jessica. I like your suggestion. I'll have a think about this over the coming days will hopefully have a good fix soon. I'll update this issue for feedback once that's done. :simple_smile:

**Comment by leejarvis** [comment]
Please check out the above commit and let me know what you think!

**Comment by ticky** [comment]
Seems like a good change to me. Thanks! 😄
