### ISSUE TITLE
Conditional 'required' option

### ISSUE THREAD

**Issue by akun1** [leejarvis/slop#259]
Is it possible to only make an option required if another option was entered?

For example:

I have 2 options, A and B.

I want B to be required ONLY if A is provided.

If A is NOT provided, then B is NOT required.

Is this possible?

**Comment by leejarvis** [comment]
There's not an easy or nice built in way to do this. You _could_ create a custom option class like this:

```ruby
# frozen_string_literal: true
$:.unshift "./lib"
require "slop"

class CustomStringOption < Slop::StringOption
  def finish(opts)
    required_option = opts.options.find do |o|
      o.flags.include?(config[:requires])
    end
    return unless required_option

    raise Slop::MissingRequiredOption unless required_option.value
  end
end

opts = Slop.parse do |o|
  o.custom_string "-a", requires: "-b"
  o.string "-b"
end
```

Note that the custom option would be on "a" rather than "b", because the `finish` method on the "b" option will never be called if the option is not provided, so we can't leverage that.

This works by checking the value of option "-b" after the parser has completed its work. If the option is nil (the default for no value provided), then `Slop::MissingRequiredOption` will be raised.

Alternatively, you could also just check for the presence of your flag name in `ARGV` or other source Array you're parsing.

**Comment by akun1** [comment]
Ahh, thank you very much for the solution and a quick reply!
