### ISSUE TITLE
Ruby v3.0.0 problem with Slop v4.8.2

### ISSUE THREAD

**Issue by MadBomber** [leejarvis/slop#261]
FYI: I'm not sure yet whether this is a problem with slop or with my cli_helper gem.  I'm using slop version 4.8.2.  My example code works under Ruby 2.6.6 and Ruby 2.7.2 but fails under Ruby 3.0.0

When I run my example code this is the failure I get:

/Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/slop-4.8.2/lib/slop/options.rb:27:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
 from /Users/dewayne/Documents/sandbox/git_repos/madbomber/cli_helper/lib/cli_helper.rb:203:in `new'
 from /Users/dewayne/Documents/sandbox/git_repos/madbomber/cli_helper/lib/cli_helper.rb:203:in `cli_helper'
 from ./cli_stub.rb:82:in `<main>'

This is my example code:
https://github.com/MadBomber/cli_helper/blob/master/example/cli_stub.rb

This is my gem where I call slop at line 203
https://github.com/MadBomber/cli_helper/blob/master/lib/cli_helper.rb

**Comment by leejarvis** [comment]
Ah yes. This is happening due to the [separation of positional and keyword arguments in Ruby 3.0](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/). You're passing a Hash to `Slop::Options.new`, but it expects a keyword list.

You can just prefix the double splat (`**`) to the hash object you're passing, like the change in #248

**Comment by MadBomber** [comment]
Obviously I never thought about that change.  Thanks!
